apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testquarkus 
  janus-idp.io/tekton: testquarkus
  backstage.io/kubernetes-id: testquarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testquarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  