apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testquarkus
  janus-idp.io/tekton: testquarkus
  backstage.io/kubernetes-id: testquarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testquarkus
resources: 
- deployment.yaml
- route.yaml
- service.yaml
